version: '3.6'
services:
  cocoa-maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:master-cli
    environment:
      DEBUG:
      VERBOSE:
    volumes:
      - ./features/fixtures/ios-swift-cocoapods/output:/app/build
      - ./features/:/app/features/
